import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChecklistProvider } from "@/contexts/ChecklistContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col max-w-2xl gap-8 m-auto p-24">
          <h1 className="text-4xl font-bold">Todo-List</h1>
          <ChecklistProvider>{children}</ChecklistProvider>
        </main>
      </body>
    </html>
  );
}
